### PR TITLE
Correct pointer alignment

### LINKED ISSUE #45: Installing from source fails on Mac OS Monterey.
Trying to install pykerberos on Apple Silicon Mac  fails with the following error

```
python setup.py install clean
```

```
clang -bundle -undefined dynamic_lookup -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/dchandra/.asdf/installs/python/3.7.12/lib -L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib -L/usr/local/lib -L/opt/homebrew/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/readline/lib -L/Users/dchandra/.asdf/installs/python/3.7.12/lib -L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib -L/usr/local/lib -L/opt/homebrew/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib build/temp.macosx-12.0-x86_64-3.7/src/kerberos.o build/temp.macosx-12.0-x86_64-3.7/src/kerberosbasic.o build/temp.macosx-12.0-x86_64-3.7/src/kerberosgss.o build/temp.macosx-12.0-x86_64-3.7/src/kerberospw.o build/temp.macosx-12.0-x86_64-3.7/src/base64.o -o build/lib.macosx-12.0-x86_64-3.7/kerberos.cpython-37m-darwin.so -L/usr/local/Cellar/krb5/1.19.2/lib -dynamic -Wl,-search_paths_first -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err
ld: warning: pointer not aligned at address 0xC00E (_krb5_mech_oid + 4 from build/temp.macosx-12.0-x86_64-3.7/src/kerberos.o)
ld: warning: pointer not aligned at address 0xC022 (_spnego_mech_oid + 4 from build/temp.macosx-12.0-x86_64-3.7/src/kerberos.o)
ld: unaligned pointer(s) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

System Details
Mac OS Monterey 12.0.1 (21A559)
Apple Silicon M1 Pro

### PR DESCRIPTION
**Pull request by devashish2203**
Changes copied from https://github.com/apple/ccs-pykerberos/commit/bfeef2739973cb59e7ef9923f8c76104223c0306?diff=split

This change allows installation of the package on Apple Silicon under Rosetta 2.
Fixes #45

### CODE REVIEW

**Comment by devashish2203** [comment]
@02strich Can you approve running the workflows on this one?

**Review by 02strich — APPROVED** [review]

**Comment by devashish2203** [comment]
Is anything else needed from me to merge this?

**Comment by 02strich** [comment]
Do you need a new pypi release?

**Comment by devashish2203** [comment]
Thanks @02strich. A pypi release would be helpful to make the package installation more seamless, but it is not super urgent as M1 macbooks are only being used by a small percentage of the team members.

**Pull request merged**
