### PR TITLE
PyCapsule_SetPointer issue

### PR DESCRIPTION
**Pull request by Stolb27**
Hi, @02strich. I have one main problem. Since now kerberos context object are destroyed automatically as soon as reference count to them becomes zero, I deleted Clean-methods. I broke this library API and the code that uses it will stop working. I see two possible solutions:
1. Restore file kerberos.c clean-methods and remove the contents from them. I have not found the possibility of a C code library call deprecated warning.
2. Write a python wrapper for the C library, which will be determined by the marked deprecated methods clean.

PS. Do I understand correctly that the code file py src / kerberos.py is purely to describe the API, and no matter what no effect?
PS2. Below is a simple example of an error reproducing on the python3. But for this we must first fix under python3 himself test.py =)

```
(kerberos_test) user@debian:~/kerberos_test$ python3 pykerberos/test.py -s HOST gssapi

*** Running GSSAPI test
Status for authGSSClientInit = Complete
Status for authGSSServerInit = Complete
Status for authGSSClientStep = Continue
Status for authGSSServerStep = Complete
Status for authGSSClientStep = Complete
Server user name: user@EXAMPLE.COM
Server target name: None
Client user name: user@EXAMPLE.COM
Status for authGSSClientClean = CompleteTraceback (most recent call last):
  File "pykerberos/test.py", line 275, in <module>
    main()
  File "pykerberos/test.py", line 99, in main
    testGSSAPI(service)
  File "pykerberos/test.py", line 162, in testGSSAPI
    print("Status for authGSSClientClean = %s" % statusText(rc))
ValueError: PyCapsule_SetPointer called with null pointer
```

### CODE REVIEW

**Comment by Stolb27** [comment]
Something like this:
https://bitbucket.org/sybren/py-deprecation

**Comment by Stolb27** [comment]
Output of test.py on py3 with last commit:
```
(kerberos_test) user@debian:~/pykerberos$ python3 pykerberos/test.py -s HOST gssapi

*** Running GSSAPI test
Status for authGSSClientInit = Complete
Status for authGSSServerInit = Complete
Status for authGSSClientStep = Continue
Status for authGSSServerStep = Complete
Status for authGSSClientStep = Complete
Server user name: user@EXAMPLE.COM
Server target name: None
Client user name: user@EXAMPLE.COM
test.py:99: RuntimeError: kerberos.authGSSClientClean is deprecated.
  testGSSAPI(service)
Status for authGSSClientClean = Complete
test.py:99: RuntimeError: kerberos.authGSSServerClean is deprecated.
  testGSSAPI(service)
Status for authGSSServerClean = Complete

*** Done
```

**Comment by 02strich** [comment]
I think this is all implemented now, would you agree?

**Comment by 02strich** [comment]
Please re-open if there is still something open.

**Pull request closed without merging**
